---
#global:
#  assets_dir: /usr/local/share/mobirc/assets

irc:
  server: 127.0.0.1
  port: 252322
  nick: netwatcher
  desc: Net Watcher
  username: netwatcher
  # password: netwatch

httpd:
  port: 5785
  title: mobirc
  lines: 40
  authorizer:
    - module: Mobirc::HTTPD::Authorizer::Cookie
      config:
        username: netwatcher
        password: 1152
    - module: Mobirc::HTTPD::Authorizer::BasicAuth
      config:
        username: netwatcher
        password: 0721
  use_cookie: 1
#  cookie_ttl: 86400
#   - module: Mobirc::HTTPD::Authorizer::EZSubscriberID
#     config:
#       au_subscriber_id: 25253252_oe.ezweb.ne.jp

