---
irc:
  server: 127.0.0.1
  port: 252322
  nick: netwatcher
  desc: Net Watcher
  username: netwatcher
  # password: netwatch

httpd:
  port: 5785
  title: mobirc
  lines: 40
  authorizer:
    - module: Mobirc::HTTPD::Authorizer::Cookie
      config:
        username: netwatcher
        password: 1152
    - module: Mobirc::HTTPD::Authorizer::BasicAuth
      config:
        username: netwatcher
        password: 0721
#   - module: Mobirc::HTTPD::Authorizer::EZSubscriberID
#     config:
#       au_subscriber_id: 25253252_oe.ezweb.ne.jp

